SELECT UGB.WRITER_ID
    , UGU.NICKNAME
    , SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGB.WRITER_ID, UGB.STATUS
HAVING UGB.STATUS = 'DONE' AND SUM(UGB.PRICE) >= 700000
ORDER BY SUM(UGB.PRICE) ASC
