## 문제풀이1

SELECT FOOD_TYPE
    , REST_ID
    , REST_NAME
    , FAVORITES
FROM REST_INFO 
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC

## 문제풀이2

WITH RankedList AS ( SELECT FOOD_TYPE
    , REST_ID
    , REST_NAME
    , FAVORITES
    , DENSE_RANK() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK
FROM REST_INFO 
)

SELECT FOOD_TYPE
    , REST_ID
    , REST_NAME
    , FAVORITES
FROM RankedList
WHERE RNK = 1
ORDER BY FOOD_TYPE DESC
