WITH TOTAL_SALES AS (
    SELECT B.BOOK_ID
        , B.AUTHOR_ID
        , B.CATEGORY
        , SUM(B.PRICE * BS.SALES) AS TOTAL
    FROM BOOK B
    JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
    WHERE BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY B.BOOK_ID, B.AUTHOR_ID, B.CATEGORY
)

SELECT TS.AUTHOR_ID
    , A.AUTHOR_NAME
    , TS.CATEGORY
    , SUM(TS.TOTAL) AS TOTAL_SALES
FROM AUTHOR A
JOIN TOTAL_SALES TS ON A.AUTHOR_ID = TS.AUTHOR_ID
GROUP BY TS.CATEGORY, TS.AUTHOR_ID, A.AUTHOR_NAME
ORDER BY TS.AUTHOR_ID, TS.CATEGORY DESC
