SELECT CC.CAR_ID
    , CC.CAR_TYPE
    , FLOOR(CC.DAILY_FEE * (1-DP.DISCOUNT_RATE/100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP ON CC.CAR_TYPE = DP.CAR_TYPE
WHERE CC.CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND (CC.CAR_TYPE ='세단' OR CC.CAR_TYPE ='SUV')
    AND DP.DURATION_TYPE = '30일 이상'
GROUP BY CC.CAR_ID
HAVING FEE > 500000 AND FEE < 2000000
ORDER BY FEE DESC, CC.CAR_TYPE, CC.CAR_ID DESC
